# Generated by Django 5.0.7 on 2024-08-01 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Students', '0002_rename_estudent_student_alter_student_options_and_more'),
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_subject', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prerequisite_subjects', to='Subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.teacher')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'T401Subject',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id_enrollment', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subject')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'T402Enrollment',
            },
        ),
    ]
