# Generated by Django 5.0.7 on 2024-08-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0002_enrollment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, null=True, related_name='prerequisite_subjects', to='Subjects.subject'),
        ),
    ]
