# Generated by Django 5.0.7 on 2024-08-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0003_alter_subject_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='prerequisite_subjects', to='Subjects.subject'),
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('subjects', models.ManyToManyField(related_name='pensums', to='Subjects.subject')),
            ],
            options={
                'verbose_name': 'Pensum',
                'verbose_name_plural': 'Pensums',
                'db_table': 'T403Pensum',
            },
        ),
    ]
