# Generated by Django 5.0.7 on 2024-08-02 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0004_alter_subject_prerequisites_pensum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensum',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='pensum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pensums', to='Subjects.pensum'),
        ),
    ]
