# Generated by Django 5.0.7 on 2024-08-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0005_remove_pensum_subjects_subject_pensum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='pensum',
        ),
        migrations.AddField(
            model_name='pensum',
            name='subjects',
            field=models.ManyToManyField(related_name='pensums', to='Subjects.subject'),
        ),
    ]
