# Generated by Django 5.0.7 on 2024-08-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0006_remove_subject_pensum_pensum_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pensum',
        ),
    ]
