# Generated by Django 5.0.7 on 2024-08-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0007_delete_pensum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id_pensum', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('subjects', models.ManyToManyField(related_name='pensums', to='Subjects.subject')),
            ],
            options={
                'verbose_name': 'Pensum',
                'verbose_name_plural': 'Pensums',
                'db_table': 'T403Pensum',
            },
        ),
    ]
