# Generated by Django 5.0.7 on 2024-08-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(db_column='id_person', editable=False, primary_key=True, serialize=False)),
                ('names', models.CharField(db_column='names', max_length=200)),
                ('last_names', models.CharField(db_column='last_names', max_length=200)),
                ('identification_number', models.CharField(db_column='identification_number', max_length=50, unique=True)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'T101Person',
            },
        ),
    ]
