# Generated by Django 5.0.7 on 2024-08-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_person',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='identification_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_names',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='names',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
