# Generated by Django 5.0.7 on 2024-08-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0002_alter_person_email_alter_person_id_person_and_more'),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudent',
            new_name='Student',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='T201Student',
        ),
    ]
